### ISSUE TITLE
vbuild -c build works but vbuild -c --dev failed

### ISSUE THREAD

**Issue by layanto** [egoist/vbuild#121] opened 2017-02-17 10:19 UTC
vbuild -c build works but vbuild -c --dev failed

```
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'vue-style-loader!css-loader' in 'C:\Projects\Baseline\client'
 @ ./src/index.js 7:0-50
 @ multi ./~/vbuild/lib/dev-client.es6 src/index.js

ERROR in ./src/index.js
Module not found: Error: Can't resolve 'vue-style-loader!css-loader' in 'C:\Projects\Baseline\client'
 @ ./src/index.js 8:0-41
 @ multi ./~/vbuild/lib/dev-client.es6 src/index.js

 ERROR  Compiling failed!
```

Content of vbuild.config.js:
```
const path = require('path')

module.exports = (options, req) => {
    const webpack = req('webpack')

    return {
        entry: 'src/index.js',
        html: {
            title: 'test-project',
            template: './src/index.html'
        },
        webpack: {
            resolve: {
                modules: [path.resolve('src')]
            },
            plugins: [
                new webpack.ProvidePlugin({
                    jQuery: "jquery",
                    $: "jquery",
                    "window.jQuery": "jquery",
                    "window.$": "jquery"
                })
            ]
        },
        vendor: ['jquery', 'lodash', 'materialize-css', 'materialize-css/dist/css/materialize.css', 'mdi/css/materialdesignicons.css', 'animate.css', 'sweetalert', 'sweetalert/dist/sweetalert.css', 'moment', 'vue', 'vue-router', 'vuex', 'vuex-router-sync', 'vee-validate']
    }
}
```

**Comment by egoist** [comment] 2017-02-17 10:53
What's the vbuild version? Any other changes to your app code or how to reproduce this.

**Comment by egoist** [comment] 2017-02-17 11:02
Seems it's caused by importing `.css` file, fixed in `v6.10.2`, webpack 2 doesn't support combining loaders with `!`

**Closed** 2017-02-17 11:03 UTC

**Comment by egoist** [comment] 2017-02-17 11:18
P.S. the `vendor` option is unnecessary now, everything you require will be split.

**Comment by layanto** [comment] 2017-02-17 12:04
Noticed that vbuild 6.x no longer split out vendor css like vbuild 5.x. Is this a bug? This is the case with or without vendor option in vbuild.config.js

**Comment by egoist** [comment] 2017-02-17 12:04
It's fixed in `master`
