### ISSUE TITLE
vbuild can't find babel when installed globally using yarn

### ISSUE THREAD

**Issue by neves** [egoist/vbuild#55] opened 2016-11-17 19:23 UTC
If I start with a new node install, 7.1.0 for example:
`nvm install node`
Install yarn first:
`npm -g install yarn`
and install vbuild using yarn:
`yarn global add vbuild`

now inside a project, try to run using:
`vbuild --dev`

```
ERROR in multi client
Module not found: Error: Can't resolve 'babel' in '/Users/neves/Documents/git/paliari-e-city-nfe'
 @ multi client

ERROR in (webpack)-hot-middleware/client-overlay.js
Module not found: Error: Can't resolve 'ansi-html' in '/Users/neves/.config/yarn/global/node_modules/webpack-hot-middleware'
 @ (webpack)-hot-middleware/client-overlay.js 25:15-35
 @ (webpack)-hot-middleware/client.js?reload=true
 @ multi client

ERROR in (webpack)-hot-middleware/client-overlay.js
Module not found: Error: Can't resolve 'html-entities' in '/Users/neves/.config/yarn/global/node_modules/webpack-hot-middleware'
 @ (webpack)-hot-middleware/client-overlay.js 40:15-39
 @ (webpack)-hot-middleware/client.js?reload=true
 @ multi client
```

Now if I install vbuild using npm, it works:
`npm -g install vbuild`
 `vbuild --dev`

**Comment by egoist** [comment] 2016-11-18 06:45
Really weird, I try to reproduce this, but ran into another issue:

```bash
nvm install 7.1.0
yarn global add vbuild
vbuild
-> fish: Unknown command 'vbuild'
yarn global remove vbuild
yarn global add vbuild
-> now it works
```

For `Can't resolve 'babel'` I haven't encountered this problem 😅

**Comment by neves** [comment] 2016-11-18 16:58
Did you try with a brand new node installation?

**Comment by egoist** [comment] 2016-11-18 16:59
Yep, I did `nvm install 7.1.0`

**Comment by neves** [comment] 2016-11-18 21:57
Do you know docker? Here is a reproducible error using docker for isolated env: (works fine if installed using `npm -g i vbuild`)
```
docker pull node
docker run -it --rm node /bin/bash
# inside docker bash
npm -g i yarn
yarn add vbuild
vbuild init todo
cd todo
npm run dev
```

> ERROR in multi client
> Module not found: Error: Can't resolve 'babel' in '/todo'
>  @ multi client
> 
> ERROR in (webpack)-hot-middleware/client.js?reload=true
> Module not found: Error: Can't resolve 'strip-ansi' in '/root/.config/yarn/global/node_modules/webpack-hot-middleware'
>  @ (webpack)-hot-middleware/client.js?reload=true 95:14-35
>  @ multi client
> 
> ERROR in (webpack)-hot-middleware/client-overlay.js
> Module not found: Error: Can't resolve 'ansi-html' in '/root/.config/yarn/global/node_modules/webpack-hot-middleware'
>  @ (webpack)-hot-middleware/client-overlay.js 25:15-35
>  @ (webpack)-hot-middleware/client.js?reload=true
>  @ multi client
> 
> ERROR in (webpack)-hot-middleware/client-overlay.js
> Module not found: Error: Can't resolve 'html-entities' in '/root/.config/yarn/global/node_modules/webpack-hot-middleware'
>  @ (webpack)-hot-middleware/client-overlay.js 40:15-39
>  @ (webpack)-hot-middleware/client.js?reload=true
>  @ multi client

**Comment by egoist** [comment] 2016-11-19 04:52
Looks like https://github.com/yarnpkg/yarn/pull/1679/files#diff-a7748843fbda5167d065231e3a2e7a1fR39 is the reason, yarn changed its directory for globally installed modules.

**Comment by egoist** [comment] 2016-11-19 05:52
Fixed in `v3.2.3`

**Closed by egoist** 2016-11-19 05:52 UTC

**Comment by jazoom** [comment] 2016-11-25 23:20
I used `yarn global add vbuild` today and nothing installed. `npm i -g vbuild` worked fine.

**Comment by egoist** [comment] 2016-11-26 05:05
@jazoom maybe you should update yarn?

**Comment by jazoom** [comment] 2016-11-26 05:13
Oops, sorry. I thought your post above was saying it was fixed in vbuild. I didn't notice that was the version for yarn.
